### ISSUE TITLE
loop name displayed wrong

### ISSUE THREAD

**Issue by ibaned** [LLNL/spot2_container#12]
Hi there!

I have the following `.cali` file:
[211111-142429_38224_TT0zGmRHyQDy.cali.txt](https://github.com/LLNL/spot2_container/files/7523437/211111-142429_38224_TT0zGmRHyQDy.cali.txt)
And the display on SPOT has changed my loop name `predictor-corrector` into `ayor-corrector`:
<img width="407" alt="Screen Shot 2021-11-11 at 2 28 34 PM" src="https://user-images.githubusercontent.com/971921/141373494-7f3731c7-a834-4814-8c33-6f932c12f2f2.png">

**Comment by mplegendre** [comment]
Odd.

I don't see this on our LLNL-deployed SPOT with your file.  I'll try with the container build...

**Comment by mplegendre** [comment]
@aschwanden1 

I can reproduce this in the container.  It looks like a problem in our compression.  From eyeballing it, I think the compressed data is flowing correctly out of the backend.  So I'm guessing there's some bug on the frontend when decompressing.  Can you look into that, Pascal?

Although as a second point, I thought that compression code was disabled.  The BE seems to disable compression when I run off of the deployment at LLNL, and enable it when I run out of the container. I don't see any configuration checks that would change the compression decision, so I'm guessing there's some git checkout difference between our LLNL live deployment and the container.  But I'm not sure how to check which spotbe/ git hash we have running in our LLNL live deployment.  And the compression (and bug) still occur if I move the spotbe/ in the container to HEAD.  Any insight here, Pascal?

**Comment by ibaned** [comment]
Thanks for digging into this @mplegendre ! It sounds like a short-term fix would be to figure out how to disable compression and then do that

**Comment by aschwanden1** [comment]
yes, I'll take a look at this right now and see if i can reproduce.  it should be very easy to turn off compression.

**Comment by aschwanden1** [comment]
Just at first glance, I think there is a bug in the dictionary translations.

In any case, I'll see if there's a quick fix.

**Comment by aschwanden1** [comment]
Ok, so I've created a fix that should fix the issue.  I've placed it in a branch here: (in spotbe) pa-fix-substring-replacement-bug and pushed it up to github.  If you wanted a quick fix, you could try that out.  

Before our next release, I'll test it more and merge into master.

**Comment by mplegendre** [comment]
That fixed it for me.

Can we still disable the compression and push that into the container?  I'm nervous about the two deployments diff'ing on a big piece of functionality.

**Comment by aschwanden1** [comment]
Yes.  It's a one line change.  i'll merge that into master and then I'll update the container spotbe to that commit.

**Comment by aschwanden1** [comment]
done.

**Comment by ibaned** [comment]
This fixes the issue for me with the latest version of this repository! Thank you both!
