### ISSUE TITLE
Support for custom base URL

### ISSUE THREAD

**Issue by dalg24** [LLNL/spot2_container#8]
cc @DavidPoliakoff

We are trying to run the SPOT container and use a reverse proxy to serve spot at https://example.com/spot/ and the notebook at https://example.com/jupyter/

We were able to update the `runspot.sh` script to make it work for the Jupyter notebook (I pasted the diff below) but it is unclear to me how to proceed with SPOT.

Here is how we configure the NGINX reverse proxy to rewrite requests

    location /spot/ {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /jupyter/ {
        proxy_pass http://localhost:8888;
        ...
    }

```diff
diff --git a/runspot.sh b/runspot.sh
index 87c774f..83d38b0 100755
--- a/runspot.sh
+++ b/runspot.sh
@@ -29,7 +29,14 @@ else
     JUPYTER_TOKEN_ARG="--NotebookApp.token="
fi
 
-/opt/conda/bin/jupyter notebook --notebook-dir=/notebooks $JUPYTER_TOKEN_ARG $JUPYTER_PORT_ARG --NotebookApp.password="" --no-browser &
+JUPYTER_BASE_URL=`/opt/conda/bin/python3 /usr/gapps/spot/readconf.py $CONFIGFILE jupyter_base_url`
+if [[ x$JUPYTER_BASE_URL != "x" && x$JUPYTER_BASE_URL != "xNone" ]]; then
+    JUPYTER_BASE_URL_ARG="--NotebookApp.base_url=$JUPYTER_BASE_URL"
+else
+    JUPYTER_BASE_URL_ARG=""
+fi
+
+/opt/conda/bin/jupyter notebook --notebook-dir=/notebooks $JUPYTER_TOKEN_ARG $JUPYTER_PORT_ARG $JUPYTER_BASE_URL_ARG --NotebookApp.password="" --no-browser --ip=0.0.0.0 &
JUPYTERPID=$!
export JUPYTERSERVER=`/opt/conda/bin/jupyter --runtime-dir`/nbserver-$JUPYTERPID.json

**Comment by mplegendre** [comment]
If you try running SPOT behind NGINX what issues does it show?

SPOT should be dynamically constructing the URLs it references using the servername as seen by the front-end.  So it could just work, though we haven't tested with NGINX so something could certainly be wrong.

**Comment by dalg24** [comment]
I try to reach `https://example.com/spot/` on my browser and get redirected to `https://example.com/login` which is missing the `/spot/`.

I also tried without setting the `SPOTW` environment variable and the SPOT server answers `Cannot GET /spot/`.

**Comment by mplegendre** [comment]
I was just working on this yesterday and believe I have the issues fixed.  In short, we had some places using absolute paths that would have been fine with relative paths.

I still have some testing, but should be posting a merging a fix soonish.

**Comment by mplegendre** [comment]
I have an initial version of this up.  There's now a spot_base_url option in backend_config.yaml that can be set to a URL prefix.

Let me know if this works for you.

**Comment by dalg24** [comment]
I just pulled 40c7932 and rebuilt the container.  I am still being redirected to `https://example.com/login`.

**Comment by mplegendre** [comment]
Can you share your backend_config.yaml?

**Comment by dalg24** [comment]
I had set the `SPOTBASEURL` environment variable instead.  I added print statement and just realized the environment was not preserved.  Rebuilding now...  Will let you know in a few minutes.

**Comment by dalg24** [comment]
OK.  `spot_base_url` in the YAML file was detected.  There is some error about being redirected too many times but that might very well be a configuration issue on the reverse proxy.  I will do more debugging later (server is in used at the moment can't mess with it too much).

Thanks for your help.

**Comment by dalg24** [comment]
It works.  @DavidPoliakoff can stop haunting me now.

I think
```diff
diff --git a/runspot.sh b/runspot.sh
index ce441d8..8f42093 100755
--- a/runspot.sh
+++ b/runspot.sh
@@ -17,7 +17,7 @@ if [[ $UID == 0 ]] ; then
         jupyterhub $JUPYTERCONF_OPT &
     fi

-    exec sudo --preserve-env=SPOTPW -u spot `realpath $0` $*
+    exec sudo --preserve-env=SPOTPW,SPOTBASEURL -u spot `realpath $0` $*
 fi

 cd /usr/gapps/spot
```
might be a good idea.  It is a bit silly that any change to the configuration invalidates the cache and retriggers a lengthy build.

**Comment by dalg24** [comment]
If anyone runs into the same issue, I resolved it by
```
location /spot/ {
    proxy_pass http://localhost:8080/;  # was missing trailing /
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
